server:
  port: 8760
spring:
  application:
    name: rh-api-gateway
  cloud:
    gateway:
      routes:
      - id: rh-pagamento
        uri: lb://rh-pagamento
        predicates:
        - Path=/pagamento/**
      - id: rh-trabalhador
        uri: lb://rh-trabalhador
        predicates:
        - Path=/trabalhadores/**
      - id: rh-usuario
        uri: lb://rh-usuario
        predicates:
        - Path=/users/**
      - id: rh-oauth
        uri: lb://rh-oauth
        predicates:
        - Path=/oauth/**
        - Cookie=Cookie,Set-Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

